sonar.projectKey=DeepseekAppKotlinNew
sonar.projectName=DeepseekAppKotlinNew
sonar.host.url=http://localhost:9000
sonar.token=sqp_cccc2908db815ca472eff4177c67e2811dbce297
sonar.sources=src
sonar.language=kotlin
sonar.sourceEncoding=UTF-8
